server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: product-service
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url : jdbc:mysql://${MYSQL_HOST:localhost}:3306/test_db
    username: root
    password: Sumi1512@
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    application:
      name: product-service
 


      
      
